services:
  cloudflare-ddns:
    build: .
    image: cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: unless-stopped
    volumes:
      - ./config:/config
    environment:
      - CLOUDFLARE_DDNS_CONFIG_PATH=/config/config.json
      - CLOUDFLARE_DDNS_LOG_PATH=/config/app.log
